package com.example.mmsvi.tabsView;

import com.example.mmsvi.tabsMethodInt.HilfeInt;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Tree;
import com.vaadin.ui.VerticalLayout;

public class HilfeTabView extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Panel Button_Panel;

	@AutoGenerated
	private VerticalLayout verticalLayout_3;

	@AutoGenerated
	private Button AboutMMS_Button;

	@AutoGenerated
	private GridLayout gridLayout_3;

	@AutoGenerated
	private Panel FAQAnzeige_Panel;

	@AutoGenerated
	private VerticalLayout verticalLayout_5;

	@AutoGenerated
	private Label label_7;

	@AutoGenerated
	private Label label_6;

	@AutoGenerated
	private Label label_5;

	@AutoGenerated
	private Label label_4;

	@AutoGenerated
	private Label label_3;

	@AutoGenerated
	private Label label_2;

	@AutoGenerated
	private Label label_1;

	@AutoGenerated
	private Panel FAQNavigation_Panel;

	@AutoGenerated
	private VerticalLayout verticalLayout_4;

	@AutoGenerated
	private Tree tree_1;

	@AutoGenerated
	private Panel FAQLabel_Panel;

	@AutoGenerated
	private VerticalLayout verticalLayout_2;

	@AutoGenerated
	private Label FAQ;

	private HilfeInt I;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	

	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HilfeTabView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	public HilfeTabView(HilfeInt I) {
		this.I=I;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// TODO Auto-generated constructor stub
	}


	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// FAQLabel_Panel
		FAQLabel_Panel = buildFAQLabel_Panel();
		mainLayout.addComponent(FAQLabel_Panel);
		
		// gridLayout_3
		gridLayout_3 = buildGridLayout_3();
		mainLayout.addComponent(gridLayout_3);
		
		// Button_Panel
		Button_Panel = buildButton_Panel();
		mainLayout.addComponent(Button_Panel);
		mainLayout.setComponentAlignment(Button_Panel, new Alignment(10));
		
		return mainLayout;
	}


	@AutoGenerated
	private Panel buildFAQLabel_Panel() {
		// common part: create layout
		FAQLabel_Panel = new Panel();
		FAQLabel_Panel.setImmediate(false);
		FAQLabel_Panel.setWidth("100.0%");
		FAQLabel_Panel.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		FAQLabel_Panel.setContent(verticalLayout_2);
		
		return FAQLabel_Panel;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(true);
		
		// FAQ
		FAQ = new Label();
		FAQ.setImmediate(false);
		FAQ.setWidth("-1px");
		FAQ.setHeight("-1px");
		FAQ.setValue("FAQ");
		verticalLayout_2.addComponent(FAQ);
		
		return verticalLayout_2;
	}


	@AutoGenerated
	private GridLayout buildGridLayout_3() {
		// common part: create layout
		gridLayout_3 = new GridLayout();
		gridLayout_3.setImmediate(false);
		gridLayout_3.setWidth("100.0%");
		gridLayout_3.setHeight("100.0%");
		gridLayout_3.setMargin(true);
		gridLayout_3.setColumns(2);
		
		// FAQNavigation_Panel
		FAQNavigation_Panel = buildFAQNavigation_Panel();
		gridLayout_3.addComponent(FAQNavigation_Panel, 0, 0);
		gridLayout_3.setComponentAlignment(FAQNavigation_Panel, new Alignment(
				48));
		
		// FAQAnzeige_Panel
		FAQAnzeige_Panel = buildFAQAnzeige_Panel();
		gridLayout_3.addComponent(FAQAnzeige_Panel, 1, 0);
		gridLayout_3.setComponentAlignment(FAQAnzeige_Panel, new Alignment(48));
		
		return gridLayout_3;
	}


	@AutoGenerated
	private Panel buildFAQNavigation_Panel() {
		// common part: create layout
		FAQNavigation_Panel = new Panel();
		FAQNavigation_Panel.setImmediate(false);
		FAQNavigation_Panel.setWidth("90.0%");
		FAQNavigation_Panel.setHeight("90.0%");
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		FAQNavigation_Panel.setContent(verticalLayout_4);
		
		return FAQNavigation_Panel;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("100.0%");
		verticalLayout_4.setHeight("100.0%");
		verticalLayout_4.setMargin(true);
		
		// tree_1
		tree_1 = new Tree();
		tree_1.setImmediate(false);
		tree_1.setWidth("392px");
		tree_1.setHeight("-1px");
		String Item1 = "Item1";
		String Item2 = "Item2";
		String Item3 = "Item3";
		String Item4 = "Item4";
		tree_1.addItem(Item1);
		tree_1.addItem(Item2);
		tree_1.addItem(Item3);
		tree_1.addItem(Item4);	
		verticalLayout_4.addComponent(tree_1);
		
		return verticalLayout_4;
	}


	@AutoGenerated
	private Panel buildFAQAnzeige_Panel() {
		// common part: create layout
		FAQAnzeige_Panel = new Panel();
		FAQAnzeige_Panel.setImmediate(false);
		FAQAnzeige_Panel.setWidth("90.0%");
		FAQAnzeige_Panel.setHeight("90.0%");
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		FAQAnzeige_Panel.setContent(verticalLayout_5);
		
		return FAQAnzeige_Panel;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.0%");
		verticalLayout_5.setHeight("100.0%");
		verticalLayout_5.setMargin(true);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		verticalLayout_5.addComponent(label_1);
		
		// label_2
		label_2 = new Label();
		label_2.setImmediate(false);
		label_2.setWidth("-1px");
		label_2.setHeight("-1px");
		label_2.setValue("Label");
		verticalLayout_5.addComponent(label_2);
		
		// label_3
		label_3 = new Label();
		label_3.setImmediate(false);
		label_3.setWidth("-1px");
		label_3.setHeight("-1px");
		label_3.setValue("Label");
		verticalLayout_5.addComponent(label_3);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("-1px");
		label_4.setHeight("-1px");
		label_4.setValue("Label");
		verticalLayout_5.addComponent(label_4);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("-1px");
		label_5.setHeight("-1px");
		label_5.setValue("Label");
		verticalLayout_5.addComponent(label_5);
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("-1px");
		label_6.setHeight("-1px");
		label_6.setValue("Label");
		verticalLayout_5.addComponent(label_6);
		
		// label_7
		label_7 = new Label();
		label_7.setImmediate(false);
		label_7.setWidth("-1px");
		label_7.setHeight("-1px");
		label_7.setValue("Label");
		verticalLayout_5.addComponent(label_7);
		
		return verticalLayout_5;
	}


	@AutoGenerated
	private Panel buildButton_Panel() {
		// common part: create layout
		Button_Panel = new Panel();
		Button_Panel.setImmediate(false);
		Button_Panel.setWidth("100px");
		Button_Panel.setHeight("30px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		Button_Panel.setContent(verticalLayout_3);
		
		return Button_Panel;
	}


	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("100.0%");
		verticalLayout_3.setMargin(false);
		
		// AboutMMS_Button
		AboutMMS_Button = new Button();
		AboutMMS_Button.setCaption("About MMS");
		AboutMMS_Button.setImmediate(true);
		AboutMMS_Button.setWidth("-1px");
		AboutMMS_Button.setHeight("-1px");
		verticalLayout_3.addComponent(AboutMMS_Button);
		
		return verticalLayout_3;
	}

}
