package com.example.mmsvi.tabsView;

import com.example.mmsvi.tabsMethod.HilfeImpl;
import com.example.mmsvi.tabsMethodInt.HilfeInt;
import com.example.mmsvi.tabsMethodInt.HomeInt;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

public class HilfeTabView extends CustomComponent {

	@AutoGenerated
	private AbsoluteLayout mainLayout;

	private HilfeInt I;
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public HilfeTabView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}


	public HilfeTabView(HilfeInt I) {
		this.I=I;
		buildMainLayout();
		setCompositionRoot(mainLayout);
		// TODO Auto-generated constructor stub
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		return mainLayout;
	}

}
