package com.example.mmsvi.tabsView;

import com.example.mmsvi.tabsMethodInt.VerwalteModulhandbuchModuluebersichtInt;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.VerticalLayout;

public class VerwalteModulhandbuchModuluebersichtTabView extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout recentlyChangedLayout;
	@AutoGenerated
	private ListSelect recentlyChangedModuleHandbooksList;
	@AutoGenerated
	private Label recentlyChangedModuleHandbooksLabel;
	@AutoGenerated
	private ListSelect recentlyChangedModulsList;
	@AutoGenerated
	private Label recentlyChangedModulesLabel;
	@AutoGenerated
	private VerticalLayout mainOverviewLayout;
	@AutoGenerated
	private HorizontalLayout moduleHandbookOverviewLayout;
	@AutoGenerated
	private VerticalLayout moduleHandbookOverviewButtonLayout;
	@AutoGenerated
	private Button moduleHandbookOverviewButton_Delete;
	@AutoGenerated
	private Button moduleHandbookOverviewButton_LeastRecent;
	@AutoGenerated
	private Button moduleHandbookOverviewButton_MostRecent;
	@AutoGenerated
	private Button moduleHandbookOverviewButton_ZA;
	@AutoGenerated
	private Button moduleHandbookOverviewButton_AZ;
	@AutoGenerated
	private VerticalLayout moduleHandbookSelectLayout;
	@AutoGenerated
	private ListSelect moduleHandbookSelectList;
	@AutoGenerated
	private Label moduleHandbookSelectLabel;
	@AutoGenerated
	private HorizontalLayout moduleOverviewLayout;
	@AutoGenerated
	private VerticalLayout moduleOverviewButtonLayout;
	@AutoGenerated
	private Button moduleOverviewButton_Delete;
	@AutoGenerated
	private Button moduleOverviewButton_LeastRecent;
	@AutoGenerated
	private Button moduleOverviewButton_MostRecent;
	@AutoGenerated
	private Button moduleOverviewButton_ZA;
	@AutoGenerated
	private Button moduleOverviewButton_AZ;
	@AutoGenerated
	private VerticalLayout moduleSelectLayout;
	@AutoGenerated
	private ListSelect moduleSelectList;
	@AutoGenerated
	private Label moduleSelectLabel;
	
	private VerwalteModulhandbuchModuluebersichtInt myInterface;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VerwalteModulhandbuchModuluebersichtTabView() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	
	public VerwalteModulhandbuchModuluebersichtTabView(VerwalteModulhandbuchModuluebersichtInt i) {
		myInterface = i;
		
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}
	

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// mainOverviewLayout
		mainOverviewLayout = buildMainOverviewLayout();
		mainLayout.addComponent(mainOverviewLayout);
		
		// recentlyChangedLayout
		recentlyChangedLayout = buildRecentlyChangedLayout();
		mainLayout.addComponent(recentlyChangedLayout);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildMainOverviewLayout() {
		// common part: create layout
		mainOverviewLayout = new VerticalLayout();
		mainOverviewLayout.setImmediate(false);
		mainOverviewLayout.setWidth("-1px");
		mainOverviewLayout.setHeight("-1px");
		mainOverviewLayout.setMargin(false);
		
		// moduleOverviewLayout
		moduleOverviewLayout = buildModuleOverviewLayout();
		mainOverviewLayout.addComponent(moduleOverviewLayout);
		
		// moduleHandbookOverviewLayout
		moduleHandbookOverviewLayout = buildModuleHandbookOverviewLayout();
		mainOverviewLayout.addComponent(moduleHandbookOverviewLayout);
		
		return mainOverviewLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildModuleOverviewLayout() {
		// common part: create layout
		moduleOverviewLayout = new HorizontalLayout();
		moduleOverviewLayout.setImmediate(false);
		moduleOverviewLayout.setWidth("-1px");
		moduleOverviewLayout.setHeight("-1px");
		moduleOverviewLayout.setMargin(true);
		moduleOverviewLayout.setSpacing(true);
		
		// moduleSelectLayout
		moduleSelectLayout = buildModuleSelectLayout();
		moduleOverviewLayout.addComponent(moduleSelectLayout);
		
		// moduleOverviewButtonLayout
		moduleOverviewButtonLayout = buildModuleOverviewButtonLayout();
		moduleOverviewLayout.addComponent(moduleOverviewButtonLayout);
		
		return moduleOverviewLayout;
	}

	@AutoGenerated
	private VerticalLayout buildModuleSelectLayout() {
		// common part: create layout
		moduleSelectLayout = new VerticalLayout();
		moduleSelectLayout.setImmediate(false);
		moduleSelectLayout.setWidth("-1px");
		moduleSelectLayout.setHeight("-1px");
		moduleSelectLayout.setMargin(false);
		
		// moduleSelectLabel
		moduleSelectLabel = new Label();
		moduleSelectLabel.setImmediate(false);
		moduleSelectLabel.setWidth("-1px");
		moduleSelectLabel.setHeight("-1px");
		moduleSelectLabel.setValue("Label");
		moduleSelectLayout.addComponent(moduleSelectLabel);
		
		// moduleSelectList
		moduleSelectList = new ListSelect();
		moduleSelectList.setImmediate(false);
		moduleSelectList.setWidth("-1px");
		moduleSelectList.setHeight("-1px");
		moduleSelectLayout.addComponent(moduleSelectList);
		
		return moduleSelectLayout;
	}

	@AutoGenerated
	private VerticalLayout buildModuleOverviewButtonLayout() {
		// common part: create layout
		moduleOverviewButtonLayout = new VerticalLayout();
		moduleOverviewButtonLayout.setImmediate(false);
		moduleOverviewButtonLayout.setWidth("-1px");
		moduleOverviewButtonLayout.setHeight("-1px");
		moduleOverviewButtonLayout.setMargin(false);
		
		// moduleOverviewButton_AZ
		moduleOverviewButton_AZ = new Button();
		moduleOverviewButton_AZ.setCaption("Button");
		moduleOverviewButton_AZ.setImmediate(true);
		moduleOverviewButton_AZ.setWidth("-1px");
		moduleOverviewButton_AZ.setHeight("-1px");
		moduleOverviewButtonLayout.addComponent(moduleOverviewButton_AZ);
		
		// moduleOverviewButton_ZA
		moduleOverviewButton_ZA = new Button();
		moduleOverviewButton_ZA.setCaption("Button");
		moduleOverviewButton_ZA.setImmediate(true);
		moduleOverviewButton_ZA.setWidth("-1px");
		moduleOverviewButton_ZA.setHeight("-1px");
		moduleOverviewButtonLayout.addComponent(moduleOverviewButton_ZA);
		
		// moduleOverviewButton_MostRecent
		moduleOverviewButton_MostRecent = new Button();
		moduleOverviewButton_MostRecent.setCaption("Button");
		moduleOverviewButton_MostRecent.setImmediate(true);
		moduleOverviewButton_MostRecent.setWidth("-1px");
		moduleOverviewButton_MostRecent.setHeight("-1px");
		moduleOverviewButtonLayout
				.addComponent(moduleOverviewButton_MostRecent);
		
		// moduleOverviewButton_LeastRecent
		moduleOverviewButton_LeastRecent = new Button();
		moduleOverviewButton_LeastRecent.setCaption("Button");
		moduleOverviewButton_LeastRecent.setImmediate(true);
		moduleOverviewButton_LeastRecent.setWidth("-1px");
		moduleOverviewButton_LeastRecent.setHeight("-1px");
		moduleOverviewButtonLayout
				.addComponent(moduleOverviewButton_LeastRecent);
		
		// moduleOverviewButton_Delete
		moduleOverviewButton_Delete = new Button();
		moduleOverviewButton_Delete.setCaption("Button");
		moduleOverviewButton_Delete.setImmediate(true);
		moduleOverviewButton_Delete.setWidth("-1px");
		moduleOverviewButton_Delete.setHeight("-1px");
		moduleOverviewButtonLayout.addComponent(moduleOverviewButton_Delete);
		
		return moduleOverviewButtonLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildModuleHandbookOverviewLayout() {
		// common part: create layout
		moduleHandbookOverviewLayout = new HorizontalLayout();
		moduleHandbookOverviewLayout.setImmediate(false);
		moduleHandbookOverviewLayout.setWidth("-1px");
		moduleHandbookOverviewLayout.setHeight("-1px");
		moduleHandbookOverviewLayout.setMargin(true);
		moduleHandbookOverviewLayout.setSpacing(true);
		
		// moduleHandbookSelectLayout
		moduleHandbookSelectLayout = buildModuleHandbookSelectLayout();
		moduleHandbookOverviewLayout.addComponent(moduleHandbookSelectLayout);
		
		// moduleHandbookOverviewButtonLayout
		moduleHandbookOverviewButtonLayout = buildModuleHandbookOverviewButtonLayout();
		moduleHandbookOverviewLayout
				.addComponent(moduleHandbookOverviewButtonLayout);
		
		return moduleHandbookOverviewLayout;
	}

	@AutoGenerated
	private VerticalLayout buildModuleHandbookSelectLayout() {
		// common part: create layout
		moduleHandbookSelectLayout = new VerticalLayout();
		moduleHandbookSelectLayout.setImmediate(false);
		moduleHandbookSelectLayout.setWidth("-1px");
		moduleHandbookSelectLayout.setHeight("-1px");
		moduleHandbookSelectLayout.setMargin(false);
		
		// moduleHandbookSelectLabel
		moduleHandbookSelectLabel = new Label();
		moduleHandbookSelectLabel.setImmediate(false);
		moduleHandbookSelectLabel.setWidth("-1px");
		moduleHandbookSelectLabel.setHeight("-1px");
		moduleHandbookSelectLabel.setValue("Label");
		moduleHandbookSelectLayout.addComponent(moduleHandbookSelectLabel);
		
		// moduleHandbookSelectList
		moduleHandbookSelectList = new ListSelect();
		moduleHandbookSelectList.setImmediate(false);
		moduleHandbookSelectList.setWidth("-1px");
		moduleHandbookSelectList.setHeight("-1px");
		moduleHandbookSelectLayout.addComponent(moduleHandbookSelectList);
		
		return moduleHandbookSelectLayout;
	}

	@AutoGenerated
	private VerticalLayout buildModuleHandbookOverviewButtonLayout() {
		// common part: create layout
		moduleHandbookOverviewButtonLayout = new VerticalLayout();
		moduleHandbookOverviewButtonLayout.setImmediate(false);
		moduleHandbookOverviewButtonLayout.setWidth("-1px");
		moduleHandbookOverviewButtonLayout.setHeight("-1px");
		moduleHandbookOverviewButtonLayout.setMargin(false);
		
		// moduleHandbookOverviewButton_AZ
		moduleHandbookOverviewButton_AZ = new Button();
		moduleHandbookOverviewButton_AZ.setCaption("Button");
		moduleHandbookOverviewButton_AZ.setImmediate(false);
		moduleHandbookOverviewButton_AZ.setWidth("-1px");
		moduleHandbookOverviewButton_AZ.setHeight("-1px");
		moduleHandbookOverviewButtonLayout
				.addComponent(moduleHandbookOverviewButton_AZ);
		
		// moduleHandbookOverviewButton_ZA
		moduleHandbookOverviewButton_ZA = new Button();
		moduleHandbookOverviewButton_ZA.setCaption("Button");
		moduleHandbookOverviewButton_ZA.setImmediate(false);
		moduleHandbookOverviewButton_ZA.setWidth("-1px");
		moduleHandbookOverviewButton_ZA.setHeight("-1px");
		moduleHandbookOverviewButtonLayout
				.addComponent(moduleHandbookOverviewButton_ZA);
		
		// moduleHandbookOverviewButton_MostRecent
		moduleHandbookOverviewButton_MostRecent = new Button();
		moduleHandbookOverviewButton_MostRecent.setCaption("Button");
		moduleHandbookOverviewButton_MostRecent.setImmediate(false);
		moduleHandbookOverviewButton_MostRecent.setWidth("-1px");
		moduleHandbookOverviewButton_MostRecent.setHeight("-1px");
		moduleHandbookOverviewButtonLayout
				.addComponent(moduleHandbookOverviewButton_MostRecent);
		
		// moduleHandbookOverviewButton_LeastRecent
		moduleHandbookOverviewButton_LeastRecent = new Button();
		moduleHandbookOverviewButton_LeastRecent.setCaption("Button");
		moduleHandbookOverviewButton_LeastRecent.setImmediate(false);
		moduleHandbookOverviewButton_LeastRecent.setWidth("-1px");
		moduleHandbookOverviewButton_LeastRecent.setHeight("-1px");
		moduleHandbookOverviewButtonLayout
				.addComponent(moduleHandbookOverviewButton_LeastRecent);
		
		// moduleHandbookOverviewButton_Delete
		moduleHandbookOverviewButton_Delete = new Button();
		moduleHandbookOverviewButton_Delete.setCaption("Button");
		moduleHandbookOverviewButton_Delete.setImmediate(false);
		moduleHandbookOverviewButton_Delete.setWidth("-1px");
		moduleHandbookOverviewButton_Delete.setHeight("-1px");
		moduleHandbookOverviewButtonLayout
				.addComponent(moduleHandbookOverviewButton_Delete);
		
		return moduleHandbookOverviewButtonLayout;
	}

	@AutoGenerated
	private VerticalLayout buildRecentlyChangedLayout() {
		// common part: create layout
		recentlyChangedLayout = new VerticalLayout();
		recentlyChangedLayout.setImmediate(false);
		recentlyChangedLayout.setWidth("-1px");
		recentlyChangedLayout.setHeight("-1px");
		recentlyChangedLayout.setMargin(false);
		
		// recentlyChangedModulesLabel
		recentlyChangedModulesLabel = new Label();
		recentlyChangedModulesLabel.setImmediate(false);
		recentlyChangedModulesLabel.setWidth("-1px");
		recentlyChangedModulesLabel.setHeight("-1px");
		recentlyChangedModulesLabel.setValue("Label");
		recentlyChangedLayout.addComponent(recentlyChangedModulesLabel);
		
		// recentlyChangedModulsList
		recentlyChangedModulsList = new ListSelect();
		recentlyChangedModulsList.setImmediate(false);
		recentlyChangedModulsList.setWidth("-1px");
		recentlyChangedModulsList.setHeight("-1px");
		recentlyChangedLayout.addComponent(recentlyChangedModulsList);
		
		// recentlyChangedModuleHandbooksLabel
		recentlyChangedModuleHandbooksLabel = new Label();
		recentlyChangedModuleHandbooksLabel.setImmediate(false);
		recentlyChangedModuleHandbooksLabel.setWidth("-1px");
		recentlyChangedModuleHandbooksLabel.setHeight("-1px");
		recentlyChangedModuleHandbooksLabel.setValue("Label");
		recentlyChangedLayout.addComponent(recentlyChangedModuleHandbooksLabel);
		
		// recentlyChangedModuleHandbooksList
		recentlyChangedModuleHandbooksList = new ListSelect();
		recentlyChangedModuleHandbooksList.setImmediate(false);
		recentlyChangedModuleHandbooksList.setWidth("-1px");
		recentlyChangedModuleHandbooksList.setHeight("-1px");
		recentlyChangedLayout.addComponent(recentlyChangedModuleHandbooksList);
		
		return recentlyChangedLayout;
	}

}
