package com.example.mmsvi.tabsView.window;

import com.example.mmsvi.tabsMethodInt.RegistrierenWindowInt;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Window;

public class RegistrierenWindow extends Window {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@AutoGenerated
	private GridLayout mainLayout=new GridLayout();

	
	private RegistrierenWindowInt I;

	private Label[] label=new Label[7];
	
	private TextField[] text=new TextField[6];
	
	private Button abschicken = new Button();
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public RegistrierenWindow(RegistrierenWindowInt I) {
		super("Registrieren");//Window Caption
		this.I=I;
		setContent(mainLayout);

		
		// top-level component properties
		

		
		// gridLayout_1
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setColumns(4);
		mainLayout.setRows(9);
		mainLayout.setSpacing(true);
		
		//Labels
		label[0]=new Label("Nachname");
		label[1]=new Label("Vorname");
		label[2]=new Label("Matrikelnummer");
		label[3]=new Label("E-Mail");
		label[4]=new Label("Passwort");
		label[5]=new Label("Wiederholen");
		label[6]=new Label("Wollen sie sich wirklich registrieren?");
		
		mainLayout.addComponent(label[0], 1, 1);
		mainLayout.addComponent(label[1], 1, 2);
		mainLayout.addComponent(label[2], 1, 3);
		mainLayout.addComponent(label[3], 1, 4);
		mainLayout.addComponent(label[4], 1, 5);
		mainLayout.addComponent(label[5], 1, 6);
		mainLayout.addComponent(label[6], 1, 7);

		//Textfields
		text[0]=new TextField();
		text[1]=new TextField();
		text[2]=new TextField();
		text[3]=new TextField();
		text[4]=new TextField();
		text[5]=new TextField();
		
		mainLayout.addComponent(text[0], 2, 1);
		mainLayout.addComponent(text[1], 2, 2);
		mainLayout.addComponent(text[2], 2, 3);
		mainLayout.addComponent(text[3], 2, 4);
		mainLayout.addComponent(text[4], 2, 5);
		mainLayout.addComponent(text[5], 2, 6);
	
		//Button
		abschicken=new Button("abschicken");
		
		mainLayout.addComponent(abschicken, 2, 7);
	}

	


}
